// se30_pace030.v - the paced kernel's instruction timing decoder (SE30_PLAN.md
// 1.17.5 item 5).  GENERATED by tools/time030/gen_pace030.py from um11.py, the
// MC68030 User's Manual's Section 11.6 tables: do not edit, regenerate.
//
// For the opcode word: the effective-address part (fea, fiea, cea, ciea or
// jea, by the manual's footnote) and the operation part of UM Equation 11-2,
// each as head, tail and I-cache-case clocks; op_cc_t is a branch's taken
// alternative (br 1 Bcc, 2 DBcc); mvm is MOVEM's addition per data cycle.
// ea_ophead: the EA's head includes the op's (the manual's "n + op head").
// The simplifications are listed in the generator's header.

`timescale 1ns/1ps

module se30_pace030 (
  input  [15:0] op,
  output reg        ea_on,
  output reg        ea_ophead,
  output reg  [4:0] ea_h,
  output reg  [1:0] ea_t,
  output reg  [5:0] ea_cc,
  output reg  [4:0] op_h,
  output reg  [1:0] op_t,
  output reg  [6:0] op_cc,
  output reg  [6:0] op_cc_t,
  output reg  [1:0] br,
  output reg  [1:0] mvm
);

  function [13:0] f_fea;   // {ophead, h[4:0], t[1:0], cc[5:0]}
    input [2:0] mode; input [2:0] rg; input lsz;
    begin
      case (mode)
        3'd0: f_fea = {1'b0, 5'd0, 2'd0, 6'd0};
        3'd1: f_fea = {1'b0, 5'd0, 2'd0, 6'd0};
        3'd2: f_fea = {1'b0, 5'd1, 2'd1, 6'd3};
        3'd3: f_fea = {1'b0, 5'd0, 2'd1, 6'd3};
        3'd4: f_fea = {1'b0, 5'd2, 2'd2, 6'd4};
        3'd5: f_fea = {1'b0, 5'd2, 2'd2, 6'd4};
        3'd6: f_fea = {1'b0, 5'd4, 2'd2, 6'd6};
        3'd7: case (rg)
          3'd0: f_fea = {1'b0, 5'd2, 2'd2, 6'd4};
          3'd1: f_fea = {1'b0, 5'd1, 2'd0, 6'd4};
          3'd2: f_fea = {1'b0, 5'd2, 2'd2, 6'd4};
          3'd3: f_fea = {1'b0, 5'd4, 2'd2, 6'd6};
          3'd4: f_fea = lsz ? {1'b0, 5'd4, 2'd0, 6'd4} : {1'b0, 5'd2, 2'd0, 6'd2};
          default: f_fea = 14'd0;
        endcase
        default: f_fea = 14'd0;
      endcase
    end
  endfunction

  function [13:0] f_fiea;   // {ophead, h[4:0], t[1:0], cc[5:0]}
    input [2:0] mode; input [2:0] rg; input lsz;
    begin
      case (mode)
        3'd0: f_fiea = lsz ? {1'b1, 5'd4, 2'd0, 6'd4} : {1'b1, 5'd2, 2'd0, 6'd2};
        3'd1: f_fiea = lsz ? {1'b1, 5'd4, 2'd0, 6'd4} : {1'b1, 5'd2, 2'd0, 6'd2};
        3'd2: f_fiea = lsz ? {1'b0, 5'd1, 2'd0, 6'd4} : {1'b0, 5'd1, 2'd1, 6'd3};
        3'd3: f_fiea = lsz ? {1'b0, 5'd4, 2'd1, 6'd7} : {1'b0, 5'd2, 2'd1, 6'd5};
        3'd4: f_fiea = lsz ? {1'b0, 5'd2, 2'd0, 6'd4} : {1'b0, 5'd2, 2'd2, 6'd4};
        3'd5: f_fiea = lsz ? {1'b0, 5'd4, 2'd0, 6'd6} : {1'b0, 5'd2, 2'd0, 6'd4};
        3'd6: f_fiea = lsz ? {1'b0, 5'd8, 2'd2, 6'd10} : {1'b0, 5'd6, 2'd2, 6'd8};
        3'd7: case (rg)
          3'd0: f_fiea = lsz ? {1'b0, 5'd6, 2'd2, 6'd8} : {1'b0, 5'd4, 2'd2, 6'd6};
          3'd1: f_fiea = lsz ? {1'b0, 5'd5, 2'd0, 6'd8} : {1'b0, 5'd3, 2'd0, 6'd6};
          3'd2: f_fiea = lsz ? {1'b0, 5'd4, 2'd0, 6'd6} : {1'b0, 5'd2, 2'd0, 6'd4};
          3'd3: f_fiea = lsz ? {1'b0, 5'd8, 2'd2, 6'd10} : {1'b0, 5'd6, 2'd2, 6'd8};
          3'd4: f_fiea = {1'b1, 5'd6, 2'd0, 6'd6};
          default: f_fiea = 14'd0;
        endcase
        default: f_fiea = 14'd0;
      endcase
    end
  endfunction

  function [13:0] f_cea;   // {ophead, h[4:0], t[1:0], cc[5:0]}
    input [2:0] mode; input [2:0] rg; input lsz;
    begin
      case (mode)
        3'd0: f_cea = {1'b0, 5'd0, 2'd0, 6'd0};
        3'd1: f_cea = {1'b0, 5'd0, 2'd0, 6'd0};
        3'd2: f_cea = {1'b1, 5'd2, 2'd0, 6'd2};
        3'd3: f_cea = {1'b0, 5'd0, 2'd0, 6'd2};
        3'd4: f_cea = {1'b1, 5'd2, 2'd0, 6'd2};
        3'd5: f_cea = {1'b1, 5'd2, 2'd0, 6'd2};
        3'd6: f_cea = {1'b1, 5'd4, 2'd0, 6'd4};
        3'd7: case (rg)
          3'd0: f_cea = {1'b1, 5'd2, 2'd0, 6'd2};
          3'd1: f_cea = {1'b1, 5'd4, 2'd0, 6'd4};
          3'd2: f_cea = {1'b1, 5'd2, 2'd0, 6'd2};
          3'd3: f_cea = {1'b1, 5'd4, 2'd0, 6'd4};
          default: f_cea = 14'd0;
        endcase
        default: f_cea = 14'd0;
      endcase
    end
  endfunction

  function [13:0] f_ciea;   // {ophead, h[4:0], t[1:0], cc[5:0]}
    input [2:0] mode; input [2:0] rg; input lsz;
    begin
      case (mode)
        3'd0: f_ciea = lsz ? {1'b1, 5'd4, 2'd0, 6'd4} : {1'b1, 5'd2, 2'd0, 6'd2};
        3'd1: f_ciea = lsz ? {1'b1, 5'd4, 2'd0, 6'd4} : {1'b1, 5'd2, 2'd0, 6'd2};
        3'd2: f_ciea = lsz ? {1'b1, 5'd4, 2'd0, 6'd4} : {1'b1, 5'd2, 2'd0, 6'd2};
        3'd3: f_ciea = lsz ? {1'b0, 5'd4, 2'd0, 6'd6} : {1'b0, 5'd2, 2'd0, 6'd4};
        3'd4: f_ciea = lsz ? {1'b1, 5'd4, 2'd0, 6'd4} : {1'b1, 5'd2, 2'd0, 6'd2};
        3'd5: f_ciea = lsz ? {1'b1, 5'd6, 2'd0, 6'd6} : {1'b1, 5'd4, 2'd0, 6'd4};
        3'd6: f_ciea = lsz ? {1'b1, 5'd8, 2'd0, 6'd8} : {1'b1, 5'd6, 2'd0, 6'd6};
        3'd7: case (rg)
          3'd0: f_ciea = lsz ? {1'b1, 5'd6, 2'd0, 6'd6} : {1'b1, 5'd4, 2'd0, 6'd4};
          3'd1: f_ciea = lsz ? {1'b1, 5'd8, 2'd0, 6'd8} : {1'b1, 5'd6, 2'd0, 6'd6};
          3'd2: f_ciea = lsz ? {1'b1, 5'd6, 2'd0, 6'd6} : {1'b1, 5'd4, 2'd0, 6'd4};
          3'd3: f_ciea = lsz ? {1'b1, 5'd8, 2'd0, 6'd8} : {1'b1, 5'd6, 2'd0, 6'd6};
          default: f_ciea = 14'd0;
        endcase
        default: f_ciea = 14'd0;
      endcase
    end
  endfunction

  function [13:0] f_jea;   // {ophead, h[4:0], t[1:0], cc[5:0]}
    input [2:0] mode; input [2:0] rg; input lsz;
    begin
      case (mode)
        3'd2: f_jea = {1'b1, 5'd2, 2'd0, 6'd2};
        3'd5: f_jea = {1'b1, 5'd4, 2'd0, 6'd4};
        3'd6: f_jea = {1'b1, 5'd6, 2'd0, 6'd6};
        3'd7: case (rg)
          3'd0: f_jea = {1'b1, 5'd2, 2'd0, 6'd2};
          3'd1: f_jea = {1'b1, 5'd2, 2'd0, 6'd2};
          3'd2: f_jea = {1'b1, 5'd4, 2'd0, 6'd4};
          3'd3: f_jea = {1'b1, 5'd6, 2'd0, 6'd6};
          default: f_jea = 14'd0;
        endcase
        default: f_jea = 14'd0;
      endcase
    end
  endfunction

  reg  [2:0] tbl;      // 0 none, 1 fea, 2 fiea, 3 cea, 4 ciea, 5 jea
  reg  [2:0] szs;      // the immediate's size: 0 from op[7:6], 1 .B, 2 .W, 3 .L, 4 MOVE's op[13:12]
  wire       lsz = (szs == 3'd0) ? (op[7:6] == 2'b10) : (szs == 3'd4) ? (op[13:12] == 2'b10) : (szs == 3'd3);
  reg [13:0] ea;

  always @* begin
    tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd0; op_cc_t = 7'd0; br = 2'd0; mvm = 2'd0;
    casez (op)
      16'b0000000000111100: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd12; op_cc_t = 7'd12; end   // ORI to CCR
      16'b0000000001111100: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd12; op_cc_t = 7'd12; end   // ORI to SR
      16'b0000001000111100: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd12; op_cc_t = 7'd12; end   // ANDI to CCR
      16'b0000001001111100: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd12; op_cc_t = 7'd12; end   // ANDI to SR
      16'b0000101000111100: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd12; op_cc_t = 7'd12; end   // EORI to CCR
      16'b0000101001111100: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd12; op_cc_t = 7'd12; end   // EORI to SR
      16'b0000100000000???: begin tbl = 3'd2; szs = 3'd2; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // BTST #,Dn
      16'b0000100000??????: begin tbl = 3'd2; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // BTST #,Mem
      16'b0000100001000???: begin tbl = 3'd2; szs = 3'd2; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // BCHG #,Dn
      16'b0000100001??????: begin tbl = 3'd2; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // BCHG #,Mem
      16'b0000100010000???: begin tbl = 3'd2; szs = 3'd2; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // BCLR #,Dn
      16'b0000100010??????: begin tbl = 3'd2; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // BCLR #,Mem
      16'b0000100011000???: begin tbl = 3'd2; szs = 3'd2; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // BSET #,Dn
      16'b0000100011??????: begin tbl = 3'd2; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // BSET #,Mem
      16'b00001110????????: begin tbl = 3'd4; szs = 3'd2; op_h = 5'd3; op_t = 2'd0; op_cc = 7'd7; op_cc_t = 7'd7; end   // MOVES EA,Rn
      16'b00001??011111100: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd24; op_cc_t = 7'd24; end   // CAS2 success
      16'b00001??011??????: begin tbl = 3'd4; szs = 3'd2; op_h = 5'd1; op_t = 2'd0; op_cc = 7'd13; op_cc_t = 7'd13; end   // CAS success
      16'b00000??011??????: begin tbl = 3'd2; szs = 3'd2; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd20; op_cc_t = 7'd20; end   // CMP2 EA,Rn
      16'b00000000??000???: begin tbl = 3'd2; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // ORI #,Dn
      16'b00000000????????: begin tbl = 3'd2; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // ORI #,Mem
      16'b00000010??000???: begin tbl = 3'd2; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // ANDI #,Dn
      16'b00000010????????: begin tbl = 3'd2; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // ANDI #,Mem
      16'b00000100??000???: begin tbl = 3'd2; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // SUBI #,Dn
      16'b00000100????????: begin tbl = 3'd2; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // SUBI #,Mem
      16'b00000110??000???: begin tbl = 3'd2; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // ADDI #,Dn
      16'b00000110????????: begin tbl = 3'd2; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // ADDI #,Mem
      16'b00001010??000???: begin tbl = 3'd2; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // EORI #,Dn
      16'b00001010????????: begin tbl = 3'd2; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // EORI #,Mem
      16'b00001100??000???: begin tbl = 3'd2; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // CMPI #,Dn
      16'b00001100????????: begin tbl = 3'd2; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // CMPI #,Mem
      16'b0000???10?001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd10; op_cc_t = 7'd10; end   // MOVEP.W (d16,An),Dn
      16'b0000???11?001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd10; op_cc_t = 7'd10; end   // MOVEP.W Dn,(d16,An)
      16'b0000???100000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // BTST Dn,Dn
      16'b0000???100??????: begin tbl = 3'd1; szs = 3'd1; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // BTST Dn,Mem
      16'b0000???101000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // BCHG Dn,Dn
      16'b0000???101??????: begin tbl = 3'd1; szs = 3'd1; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // BCHG Dn,Mem
      16'b0000???110000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // BCLR Dn,Dn
      16'b0000???110??????: begin tbl = 3'd1; szs = 3'd1; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // BCLR Dn,Mem
      16'b0000???111000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // BSET Dn,Dn
      16'b0000???111??????: begin tbl = 3'd1; szs = 3'd1; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // BSET Dn,Mem
      16'b0001???000??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // MOVE EA,Dn
      16'b0001???001??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // MOVE EA,An
      16'b0001???01000????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // MOVE Rn,(An)
      16'b0001???010??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE SOURCE,(An)
      16'b0001???01100????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // MOVE Rn,(An)+
      16'b0001???011??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE SOURCE,(An)+
      16'b0001???10000????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd2; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE Rn,-(An)
      16'b0001???100??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE SOURCE,-(An)
      16'b0001???101??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE EA,(d16,An)
      16'b0001???110??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // MOVE EA,(d8,An,Xn)
      16'b0001000111??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE EA,(xxx).W
      16'b0001001111??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // MOVE EA,(xxx).L
      16'b0011???000??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // MOVE EA,Dn
      16'b0011???001??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // MOVE EA,An
      16'b0011???01000????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // MOVE Rn,(An)
      16'b0011???010??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE SOURCE,(An)
      16'b0011???01100????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // MOVE Rn,(An)+
      16'b0011???011??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE SOURCE,(An)+
      16'b0011???10000????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd2; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE Rn,-(An)
      16'b0011???100??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE SOURCE,-(An)
      16'b0011???101??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE EA,(d16,An)
      16'b0011???110??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // MOVE EA,(d8,An,Xn)
      16'b0011000111??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE EA,(xxx).W
      16'b0011001111??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // MOVE EA,(xxx).L
      16'b0010???000??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // MOVE EA,Dn
      16'b0010???001??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // MOVE EA,An
      16'b0010???01000????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // MOVE Rn,(An)
      16'b0010???010??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE SOURCE,(An)
      16'b0010???01100????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // MOVE Rn,(An)+
      16'b0010???011??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE SOURCE,(An)+
      16'b0010???10000????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd2; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE Rn,-(An)
      16'b0010???100??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE SOURCE,-(An)
      16'b0010???101??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE EA,(d16,An)
      16'b0010???110??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // MOVE EA,(d8,An,Xn)
      16'b0010000111??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE EA,(xxx).W
      16'b0010001111??????: begin tbl = 3'd1; szs = 3'd4; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // MOVE EA,(xxx).L
      16'b0100101011111100: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd18; op_cc_t = 7'd18; end   // Illegal instruction
      16'b0100000011000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE SR,Dn
      16'b0100000011??????: begin tbl = 3'd3; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE SR,Mem
      16'b0100001011000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE CCR,Dn
      16'b0100001011??????: begin tbl = 3'd3; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE CCR,Mem
      16'b0100010011000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE Dn,CCR
      16'b0100010011??????: begin tbl = 3'd3; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE EA,CCR
      16'b0100011011??????: begin tbl = 3'd1; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd8; op_cc_t = 7'd8; end   // MOVE EA,SR
      16'b01000000??000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // NEGX Dn
      16'b01000000????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // NEGX Mem
      16'b01000010??000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // CLR Dn
      16'b01000010????????: begin tbl = 3'd3; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // CLR Mem
      16'b01000100??000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // NEG Dn
      16'b01000100????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // NEG Mem
      16'b01000110??000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // NOT Dn
      16'b01000110????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // NOT Mem
      16'b0100100000001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // LINK.L
      16'b0100100000000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // NBCD Dn
      16'b0100100000??????: begin tbl = 3'd1; szs = 3'd1; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // NBCD Dn
      16'b0100100001000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // SWAP Dn
      16'b0100100001001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd1; op_t = 2'd0; op_cc = 7'd9; op_cc_t = 7'd9; end   // BKPT
      16'b0100100001??????: begin tbl = 3'd3; szs = 3'd0; op_h = 5'd0; op_t = 2'd2; op_cc = 7'd4; op_cc_t = 7'd4; end   // PEA
      16'b010010001?000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // EXT Dn
      16'b0100100111000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // EXT Dn
      16'b010010001???????: begin tbl = 3'd4; szs = 3'd2; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; mvm = 2'd0; end   // MOVEM RL,EA
      16'b010011001???????: begin tbl = 3'd4; szs = 3'd2; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd8; op_cc_t = 7'd8; mvm = 2'd2; end   // MOVEM EA,RL
      16'b0100101011000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // TAS Dn
      16'b0100101011??????: begin tbl = 3'd3; szs = 3'd0; op_h = 5'd3; op_t = 2'd0; op_cc = 7'd12; op_cc_t = 7'd12; end   // TAS Mem
      16'b01001010??000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // TST Dn
      16'b01001010????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // TST Mem
      16'b0100110000??????: begin tbl = 3'd2; szs = 3'd2; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd44; op_cc_t = 7'd44; end   // MULS.L EA,Dn
      16'b0100110001??????: begin tbl = 3'd2; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd78; op_cc_t = 7'd78; end   // DIVU.L EA,Dn
      16'b010011100100????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd18; op_cc_t = 7'd18; end   // TRAP #n
      16'b0100111001010???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // LINK.W
      16'b0100111001011???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd5; op_cc_t = 7'd5; end   // UNLK
      16'b0100111001100???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE An,USP
      16'b0100111001101???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // MOVE USP,An
      16'b0100111001110000: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd127; op_cc_t = 7'd127; end   // RESET instruction
      16'b0100111001110001: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // NOP
      16'b0100111001110010: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd8; op_cc_t = 7'd8; end   // STOP
      16'b0100111001110011: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd1; op_t = 2'd0; op_cc = 7'd18; op_cc_t = 7'd18; end   // RTE four word
      16'b0100111001110100: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd10; op_cc_t = 7'd10; end   // RTD
      16'b0100111001110101: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd1; op_t = 2'd0; op_cc = 7'd9; op_cc_t = 7'd9; end   // RTS
      16'b0100111001110110: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // TRAPV no trap
      16'b0100111001110111: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd1; op_t = 2'd0; op_cc = 7'd12; op_cc_t = 7'd12; end   // RTR
      16'b0100111001111010: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // MOVEC Cr,Rn
      16'b0100111001111011: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // MOVEC Rn,Cr-A
      16'b0100111010??????: begin tbl = 3'd5; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // JSR
      16'b0100111011??????: begin tbl = 3'd5; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // JMP
      16'b0100???111??????: begin tbl = 3'd3; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // LEA
      16'b0100???1?0000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd8; op_t = 2'd0; op_cc = 7'd8; op_cc_t = 7'd8; end   // CHK Dn,Dn
      16'b0100???1?0??????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd8; op_cc_t = 7'd8; end   // CHK EA,Dn
      16'b0101000111001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd10; op_t = 2'd0; op_cc = 7'd10; op_cc_t = 7'd6; br = 2'd2; end   // DBcc expired
      16'b0101????11001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; br = 2'd2; end   // DBcc true
      16'b0101????11111010: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // TRAPcc.W no trap
      16'b0101????11111011: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd8; op_t = 2'd0; op_cc = 7'd8; op_cc_t = 7'd8; end   // TRAPcc.L no trap
      16'b0101????11111100: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // TRAPcc no trap
      16'b0101????11000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // Scc Dn
      16'b0101????11??????: begin tbl = 3'd3; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd5; op_cc_t = 7'd5; end   // Scc Mem
      16'b0101???0??00????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // ADDQ #,Rn
      16'b0101???0????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // ADDQ #,Mem
      16'b0101???1??00????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // SUBQ #,Rn
      16'b0101???1????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // SUBQ #,Mem
      16'b01100001????????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // BSR
      16'b0110????00000000: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; br = 2'd1; end   // Bcc.W not taken
      16'b0110????11111111: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; br = 2'd1; end   // Bcc.L not taken
      16'b0110????????????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd6; br = 2'd1; end   // Bcc.B not taken
      16'b0111???0????????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // MOVEQ #,Dn
      16'b1000???011000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd44; op_cc_t = 7'd44; end   // DIVU.W Dn,Dn
      16'b1000???011??????: begin tbl = 3'd1; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd44; op_cc_t = 7'd44; end   // DIVU.W EA,Dn
      16'b1000???111000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd56; op_cc_t = 7'd56; end   // DIVS.W Dn,Dn
      16'b1000???111??????: begin tbl = 3'd1; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd56; op_cc_t = 7'd56; end   // DIVS.W EA,Dn
      16'b1000???100000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // SBCD Dn,Dn
      16'b1000???100001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd1; op_cc = 7'd13; op_cc_t = 7'd13; end   // SBCD -(An),-(An)
      16'b1000???101000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // PACK Dn,Dn,#
      16'b1000???101001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd1; op_cc = 7'd11; op_cc_t = 7'd11; end   // PACK -(An),-(An),#
      16'b1000???110000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd8; op_t = 2'd0; op_cc = 7'd8; op_cc_t = 7'd8; end   // UNPK Dn,Dn,#
      16'b1000???110001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd1; op_cc = 7'd11; op_cc_t = 7'd11; end   // UNPK -(An),-(An),#
      16'b1000???0??000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // OR Dn,Dn
      16'b1000???0????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // OR EA,Dn
      16'b1000???1????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // OR Dn,EA
      16'b1001???01100????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // SUBA.W Rn,An
      16'b1001???011??????: begin tbl = 3'd1; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // SUBA.W EA,An
      16'b1001???11100????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // SUBA.L Rn,An
      16'b1001???111??????: begin tbl = 3'd1; szs = 3'd3; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // SUBA.L EA,An
      16'b1001???1??000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // SUBX Dn,Dn
      16'b1001???1??001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd1; op_cc = 7'd9; op_cc_t = 7'd9; end   // SUBX -(An),-(An)
      16'b1001???0??00????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // SUB Rn,Dn
      16'b1001???0????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // SUB EA,Dn
      16'b1001???1????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // SUB Dn,EA
      16'b1010????????????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd18; op_cc_t = 7'd18; end   // A-line trap
      16'b1011???01100????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // CMPA Rn,An
      16'b1011???011??????: begin tbl = 3'd1; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // CMPA EA,An
      16'b1011???11100????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // CMPA Rn,An
      16'b1011???111??????: begin tbl = 3'd1; szs = 3'd3; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // CMPA EA,An
      16'b1011???1??001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd8; op_cc_t = 7'd8; end   // CMPM (An)+,(An)+
      16'b1011???1??000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // EOR Dn,Dn
      16'b1011???1????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // EOR Dn,EA
      16'b1011???0??00????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // CMP Rn,Dn
      16'b1011???0????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // CMP EA,Dn
      16'b1100???011??????: begin tbl = 3'd1; szs = 3'd2; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd28; op_cc_t = 7'd28; end   // MULU.W EA,Dn
      16'b1100???111??????: begin tbl = 3'd1; szs = 3'd2; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd28; op_cc_t = 7'd28; end   // MULS.W EA,Dn
      16'b1100???100000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // ABCD Dn,Dn
      16'b1100???100001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd1; op_cc = 7'd13; op_cc_t = 7'd13; end   // ABCD -(An),-(An)
      16'b1100???101000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // EXG Ry,Rx
      16'b1100???101001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // EXG Ry,Rx
      16'b1100???110001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // EXG Ry,Rx
      16'b1100???0??000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // AND Dn,Dn
      16'b1100???0????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // AND EA,Dn
      16'b1100???1????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // AND Dn,EA
      16'b1101???01100????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // ADDA.W Rn,An
      16'b1101???011??????: begin tbl = 3'd1; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // ADDA.W EA,An
      16'b1101???11100????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // ADDA.L Rn,An
      16'b1101???111??????: begin tbl = 3'd1; szs = 3'd3; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // ADDA.L EA,An
      16'b1101???1??000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // ADDX Dn,Dn
      16'b1101???1??001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd1; op_cc = 7'd9; op_cc_t = 7'd9; end   // ADDX -(An),-(An)
      16'b1101???0??00????: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // ADD Rn,Dn
      16'b1101???0????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd2; op_cc_t = 7'd2; end   // ADD EA,Dn
      16'b1101???1????????: begin tbl = 3'd1; szs = 3'd0; op_h = 5'd0; op_t = 2'd1; op_cc = 7'd3; op_cc_t = 7'd3; end   // ADD Dn,EA
      16'b1110100011000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd8; op_t = 2'd0; op_cc = 7'd8; op_cc_t = 7'd8; end   // BFTST Dn
      16'b1110100011??????: begin tbl = 3'd4; szs = 3'd2; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd10; op_cc_t = 7'd10; end   // BFTST Mem<5
      16'b1110100111000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd10; op_t = 2'd0; op_cc = 7'd10; op_cc_t = 7'd10; end   // BFEXTU Dn
      16'b1110100111??????: begin tbl = 3'd4; szs = 3'd2; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd12; op_cc_t = 7'd12; end   // BFEXTU Mem<5
      16'b1110101011000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd14; op_t = 2'd0; op_cc = 7'd14; op_cc_t = 7'd14; end   // BFCHG Dn
      16'b1110101011??????: begin tbl = 3'd4; szs = 3'd2; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd14; op_cc_t = 7'd14; end   // BFCHG Mem<5
      16'b1110101111000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd10; op_t = 2'd0; op_cc = 7'd10; op_cc_t = 7'd10; end   // BFEXTS Dn
      16'b1110101111??????: begin tbl = 3'd4; szs = 3'd2; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd12; op_cc_t = 7'd12; end   // BFEXTS Mem<5
      16'b1110110011000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd14; op_t = 2'd0; op_cc = 7'd14; op_cc_t = 7'd14; end   // BFCLR Dn
      16'b1110110011??????: begin tbl = 3'd4; szs = 3'd2; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd14; op_cc_t = 7'd14; end   // BFCLR Mem<5
      16'b1110110111000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd20; op_t = 2'd0; op_cc = 7'd20; op_cc_t = 7'd20; end   // BFFFO Dn
      16'b1110110111??????: begin tbl = 3'd4; szs = 3'd2; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd22; op_cc_t = 7'd22; end   // BFFFO Mem<5
      16'b1110111011000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd14; op_t = 2'd0; op_cc = 7'd14; op_cc_t = 7'd14; end   // BFSET Dn
      16'b1110111011??????: begin tbl = 3'd4; szs = 3'd2; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd14; op_cc_t = 7'd14; end   // BFSET Mem<5
      16'b1110111111000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd12; op_t = 2'd0; op_cc = 7'd12; op_cc_t = 7'd12; end   // BFINS Dn
      16'b1110111111??????: begin tbl = 3'd4; szs = 3'd2; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd12; op_cc_t = 7'd12; end   // BFINS Mem<5
      16'b1110000011??????: begin tbl = 3'd1; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // ASR Mem
      16'b1110000111??????: begin tbl = 3'd1; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // ASL Mem
      16'b1110001?11??????: begin tbl = 3'd1; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // LSd Mem
      16'b1110010?11??????: begin tbl = 3'd1; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // ROXd Mem
      16'b1110011?11??????: begin tbl = 3'd1; szs = 3'd2; op_h = 5'd0; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // ROd Mem
      16'b1110???0??000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // ASR #,Dy
      16'b1110???1??000???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd2; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // ASL #,Dy
      16'b1110???0??100???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // ASR Dx,Dy
      16'b1110???1??100???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd8; op_cc_t = 7'd8; end   // ASL Dx,Dy
      16'b1110??????001???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd4; op_cc_t = 7'd4; end   // LSd #,Dy
      16'b1110??????101???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // LSd Dx,Dy
      16'b1110??????010???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd10; op_t = 2'd0; op_cc = 7'd12; op_cc_t = 7'd12; end   // ROXd Dn
      16'b1110??????110???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd10; op_t = 2'd0; op_cc = 7'd12; op_cc_t = 7'd12; end   // ROXd Dn
      16'b1110??????011???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd4; op_t = 2'd0; op_cc = 7'd6; op_cc_t = 7'd6; end   // ROd #,Dy
      16'b1110??????111???: begin tbl = 3'd0; szs = 3'd0; op_h = 5'd6; op_t = 2'd0; op_cc = 7'd8; op_cc_t = 7'd8; end   // ROd Dx,Dy
      16'b1111????????????: ;   // the coprocessors: unpaced
      default: ;
    endcase
    case (tbl)
      3'd1: ea = f_fea(op[5:3], op[2:0], lsz);
      3'd2: ea = f_fiea(op[5:3], op[2:0], lsz);
      3'd3: ea = f_cea(op[5:3], op[2:0], lsz);
      3'd4: ea = f_ciea(op[5:3], op[2:0], lsz);
      3'd5: ea = f_jea(op[5:3], op[2:0], lsz);
      default: ea = 14'd0;
    endcase
    ea_on = (tbl != 3'd0);
    {ea_ophead, ea_h, ea_t, ea_cc} = ea;
  end

endmodule
